name: deploy-docs

on:
  push:
    branches: [main]
    paths:
      - "apps/web/**"
      - ".github/workflows/deploy-docs.yml"
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    uses: cyber-civitas/.github/.github/workflows/pnpm-deploy-pages.yml@v1
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      build-script: pnpm --filter website build
      path: apps/web/dist
